export enum Role {
  PROCUREMENT_OFFICER = 'procurement_officer',
  PROCUREMENT_MANAGER = 'procurement_manager',
  FINANCE_OFFICER = 'finance_officer',
  FINANCE_MANAGER = 'finance_manager',
  CUSTOMS_OFFICER = 'customs_officer',
  WAREHOUSE_MANAGER = 'warehouse_manager',
  GENERAL_MANAGER = 'general_manager',
  SYSTEM_ADMIN = 'system_admin',
}

export enum Permission {
  SUPPLIER_READ = 'suppliers:read',
  SUPPLIER_WRITE = 'suppliers:write',
  PO_READ = 'po:read',
  PO_WRITE = 'po:write',
  PO_APPROVE_TIER1 = 'po:approve:tier1',
  PO_APPROVE_TIER2 = 'po:approve:tier2',
  PO_APPROVE_TIER3 = 'po:approve:tier3',
  LC_READ = 'lc:read',
  LC_WRITE = 'lc:write',
  LC_APPROVE = 'lc:approve',
  SHIPMENT_READ = 'shipment:read',
  SHIPMENT_WRITE = 'shipment:write',
  CUSTOMS_READ = 'customs:read',
  CUSTOMS_WRITE = 'customs:write',
  TARIFFS_READ = 'tariffs:read',
  TARIFFS_WRITE = 'tariffs:write',
  COST_READ = 'cost:read',
  COST_WRITE = 'cost:write',
  COST_APPROVE = 'cost:approve',
  COST_FINALIZE = 'cost:finalize',
  VARIANCE_APPROVE = 'variance:approve',
  GRN_READ = 'grn:read',
  GRN_WRITE = 'grn:write',
  REPORT_LANDED_COST_SHIPMENT_READ = 'report:landed_cost_shipment:read',
  REPORT_LANDED_COST_ITEM_READ = 'report:landed_cost_item:read',
  REPORT_LANDED_COST_SUPPLIER_READ = 'report:landed_cost_supplier:read',
  REPORT_IMPORT_COST_SUMMARY_READ = 'report:import_cost_summary:read',
  REPORT_LC_STATUS_READ = 'report:lc_status:read',
  REPORT_CUSTOMS_DUTY_READ = 'report:customs_duty:read',
  REPORT_SHIPMENT_STATUS_READ = 'report:shipment_status:read',
  REPORT_COST_VARIANCE_READ = 'report:cost_variance:read',
  REPORT_SUPPLIER_PERFORMANCE_READ = 'report:supplier_performance:read',
  AUDIT_READ = 'audit:read',
  ADMIN_ALL = 'admin:all',
  SETTINGS_READ = 'settings:read',
  SETTINGS_WRITE = 'settings:write',
  RATES_READ = 'rates:read',
  RATES_WRITE = 'rates:write',
  USERS_READ = 'users:read',
  USERS_WRITE = 'users:write',
  ITEM_READ = 'items:read',
  ITEM_WRITE = 'items:write',
}

export const RolePermission: Record<Role, Permission[]> = {
  [Role.SYSTEM_ADMIN]: [Permission.ADMIN_ALL],

  [Role.PROCUREMENT_OFFICER]: [
    Permission.REPORT_LANDED_COST_SHIPMENT_READ,
    Permission.REPORT_LANDED_COST_ITEM_READ,
    Permission.REPORT_LANDED_COST_SUPPLIER_READ,
    Permission.REPORT_LC_STATUS_READ,
    Permission.REPORT_SHIPMENT_STATUS_READ,
    Permission.SUPPLIER_READ,
    Permission.SUPPLIER_WRITE,
    Permission.ITEM_READ,
    Permission.PO_READ,
    Permission.ITEM_READ,
    Permission.PO_WRITE,
    Permission.SHIPMENT_READ,
    Permission.SHIPMENT_WRITE,
  ],
  [Role.PROCUREMENT_MANAGER]: [
    Permission.REPORT_LANDED_COST_SHIPMENT_READ,
    Permission.REPORT_LANDED_COST_ITEM_READ,
    Permission.REPORT_LANDED_COST_SUPPLIER_READ,
    Permission.REPORT_LC_STATUS_READ,
    Permission.REPORT_SHIPMENT_STATUS_READ,
    Permission.REPORT_SUPPLIER_PERFORMANCE_READ,
    Permission.SUPPLIER_READ,
    Permission.ITEM_READ,
    Permission.SUPPLIER_WRITE,
    Permission.ITEM_WRITE,
    Permission.PO_READ,
    Permission.ITEM_READ,
    Permission.PO_WRITE,
    Permission.PO_APPROVE_TIER1,
    Permission.SHIPMENT_READ,
    Permission.SHIPMENT_WRITE,
    Permission.REPORT_LANDED_COST_SUPPLIER_READ,
  ],
  [Role.FINANCE_OFFICER]: [
    Permission.REPORT_LANDED_COST_ITEM_READ,
    Permission.REPORT_LC_STATUS_READ,
    Permission.REPORT_CUSTOMS_DUTY_READ,
    Permission.PO_READ,
    Permission.ITEM_READ,
    Permission.LC_READ,
    Permission.LC_WRITE,
    Permission.SHIPMENT_READ,
    Permission.COST_READ,
    Permission.COST_WRITE,
    Permission.RATES_READ,
    Permission.RATES_WRITE,
    Permission.TARIFFS_READ,
  ],
  [Role.FINANCE_MANAGER]: [
    Permission.REPORT_LANDED_COST_SHIPMENT_READ,
    Permission.REPORT_LANDED_COST_ITEM_READ,
    Permission.REPORT_IMPORT_COST_SUMMARY_READ,
    Permission.REPORT_LC_STATUS_READ,
    Permission.REPORT_CUSTOMS_DUTY_READ,
    Permission.REPORT_COST_VARIANCE_READ,
    Permission.PO_READ,
    Permission.ITEM_READ,
    Permission.LC_READ,
    Permission.LC_WRITE,
    Permission.LC_APPROVE,
    Permission.SHIPMENT_READ,
    Permission.COST_READ,
    Permission.COST_WRITE,
    Permission.COST_APPROVE,
    Permission.COST_FINALIZE,
    Permission.VARIANCE_APPROVE,
    Permission.REPORT_LANDED_COST_SUPPLIER_READ,
    Permission.SETTINGS_READ,
    Permission.SETTINGS_WRITE,
    Permission.RATES_READ,
    Permission.RATES_WRITE,
    Permission.TARIFFS_READ,
  ],
  [Role.CUSTOMS_OFFICER]: [
    Permission.REPORT_CUSTOMS_DUTY_READ,
    Permission.SHIPMENT_READ,
    Permission.CUSTOMS_READ,
    Permission.CUSTOMS_WRITE,
    Permission.TARIFFS_READ,
    Permission.TARIFFS_WRITE,
    Permission.COST_READ,
    Permission.COST_WRITE,
  ],
  [Role.WAREHOUSE_MANAGER]: [
    Permission.REPORT_SHIPMENT_STATUS_READ,
    Permission.SHIPMENT_READ,
    Permission.GRN_READ,
    Permission.GRN_WRITE,
  ],
  [Role.GENERAL_MANAGER]: [
    Permission.PO_READ,
    Permission.ITEM_READ,
    Permission.PO_APPROVE_TIER2,
    Permission.PO_APPROVE_TIER3,
    Permission.LC_READ,
    Permission.LC_APPROVE,
    Permission.REPORT_LANDED_COST_SUPPLIER_READ,
    Permission.AUDIT_READ,
  ],
};
